### ISSUE TITLE
Add pictures

### ISSUE THREAD

**Issue by MikeSaliba** [axe-head-watchmakers/axe-head-watchmakers.github.io#8]
All the pictures are available at https://www.brookeelizabethart.com/axeheadwatches/  the download code is 4896. 

Every watch should be the nature shot, then when you click on it for more info goes to the catalog shot.

Just name each one 'Watch 1" "Watch 2" in the order in which you enter them. I'll then look and make a list that goes like "watch 1 is called x and cost y"

If you need more guidance than that, give me call

**Comment by ao5357** [comment]
@MikeSaliba Pictures added to the codebase but not actively used. You can review the thumbnails on the site at https://axeheadwatch.com/docs/design/assets/jpg/ or in the codebase as https://github.com/axe-head-watchmakers/axe-head-watchmakers.github.io/tree/gh-pages/assets/images/products
